# Generated by Django 2.2.7 on 2020-06-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200601_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answera',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='answerb',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='answerc',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='answerd',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='questions',
            name='correctanswer',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='level',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='technology',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
