# Generated by Django 2.2.7 on 2020-06-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200601_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='qid',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
