# Generated by Django 2.2.7 on 2020-06-04 03:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_questions_qid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
