# Generated by Django 2.2.7 on 2020-06-04 04:33

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200604_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
