# Generated by Django 2.2.7 on 2020-06-04 15:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200604_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
