# Generated by Django 2.2.7 on 2020-06-04 15:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200604_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answera',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answerb',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answerc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answerd',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
