# Generated by Django 2.2.7 on 2020-06-05 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20200604_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default=True, max_length=100)),
                ('technology', models.CharField(default=True, max_length=100)),
                ('qid', models.CharField(default=True, max_length=100)),
                ('stdanswer', models.CharField(default=True, max_length=100)),
                ('attemptid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
