# Generated by Django 2.2.7 on 2020-06-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='attemptid',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
