# Generated by Django 3.0.3 on 2020-06-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200605_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
