# Generated by Django 3.0.3 on 2020-06-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200606_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='status',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
