# Generated by Django 3.0.3 on 2020-06-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_answers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='status',
            field=models.CharField(default='NotStarted', max_length=100),
        ),
    ]
